-- Re-runnable with psql or the Management API. All fixtures and room changes roll back.
begin;
create function pg_temp.assert(ok boolean, description text) returns void language plpgsql as $$
begin if ok is distinct from true then raise exception 'FAIL: %', description; end if; raise notice 'PASS: %', description; end $$;
create function pg_temp.denied(query text, description text) returns void language plpgsql as $$
begin
  begin execute query; exception when others then raise notice 'PASS: % (%)', description, sqlerrm; return; end;
  raise exception 'FAIL: % was allowed', description;
end $$;
select pg_temp.assert(not has_table_privilege('anon','public.poll_answers','SELECT'), 'anonymous callers cannot read raw responses');
select pg_temp.assert(not has_table_privilege('authenticated','public.poll_answers','SELECT'), 'signed-in callers cannot read raw responses');
select pg_temp.assert(not has_function_privilege('anon','public.poll_document(bigint)','EXECUTE'), 'private document helper is not public');
select pg_temp.assert(not has_function_privilege('anon','public.poll_library()','EXECUTE'), 'anonymous callers cannot get totals');
select pg_temp.assert(not has_function_privilege('anon','public.poll_save(bigint,text,text,text,text[])','EXECUTE'), 'anonymous callers cannot create questions');
select pg_temp.assert(not has_function_privilege('anon','public.poll_action(bigint,text)','EXECUTE'), 'anonymous callers cannot manage questions');
set local role authenticated;
select set_config('request.jwt.claims','{"email":"member@example.test"}',true);
select pg_temp.denied('select public.poll_library()', 'non-admin cannot get totals');
select pg_temp.denied($q$select public.poll_save(null,'Bad','','single',array['A','B'])$q$, 'non-admin cannot create questions');
select pg_temp.denied($q$select public.poll_action(1,'open')$q$, 'non-admin cannot open questions');
select set_config('request.jwt.claims','{"email":"iamkcerb@gmail.com"}',true);
with fixture as (select public.poll_save(null,'Test multi input','','multi',array['A','B','C']) as multi) select set_config('test.multi', multi::text, true) from fixture;
with fixture as (select public.poll_save(null,'Test single input','','single',array['X','Y']) as single) select set_config('test.single', single::text, true) from fixture;
with fixture as (select public.poll_save(null,'Disposable draft','','single',array['X','Y']) as disposable) select set_config('test.disposable', disposable::text, true) from fixture;
select public.poll_action(current_setting('test.disposable')::bigint,'delete');
select pg_temp.assert(not exists(select 1 from jsonb_array_elements(public.poll_library()->'polls') p where (p->>'id')::bigint = current_setting('test.disposable')::bigint), 'delete removes an unanswered draft');
select pg_temp.denied($q$select public.poll_save(null,'Bad','','single',array['A'])$q$, 'at least two options required');
select public.poll_action(current_setting('test.multi')::bigint,'open');
with fixture as (select (public.poll_current()->'options'->0->>'id')::bigint as a, (public.poll_current()->'options'->1->>'id')::bigint as b, public.poll_current()->>'opened_at' as epoch) select set_config('test.a', a::text, true), set_config('test.b', b::text, true), set_config('test.epoch', epoch::text, true) from fixture;
select pg_temp.assert(not (public.poll_current() ? 'results') and not (public.poll_current() ? 'respondents') and public.poll_current()->>'locked' = 'false', 'public document hides all response metadata');
set local role anon;
select set_config('request.jwt.claims','{}',true);
select pg_temp.assert((public.poll_current()->>'id')::bigint = current_setting('test.multi')::bigint, 'anonymous callers see the current question');
select pg_temp.assert(public.poll_my_answer(current_setting('test.multi')::bigint,repeat('a',72)) = '{"selection":[],"revision":0}'::jsonb, 'new browser starts empty');
select pg_temp.assert((public.poll_answer(current_setting('test.multi')::bigint,repeat('a',72),array[current_setting('test.a')::bigint,current_setting('test.b')::bigint]::bigint[],0,current_setting('test.epoch')::timestamptz)->>'revision')::int = 1, 'multi answer saves atomically');
select pg_temp.assert(jsonb_array_length(public.poll_my_answer(current_setting('test.multi')::bigint,repeat('a',72))->'selection') = 2, 'same browser restores both selections');
select pg_temp.assert(public.poll_my_answer(current_setting('test.multi')::bigint,repeat('b',72)) = '{"selection":[],"revision":0}'::jsonb, 'another browser cannot restore someone else’s response');
select pg_temp.denied(format('select public.poll_answer(%s,repeat(''a'',72),array[%s]::bigint[],0,%L)',current_setting('test.multi')::bigint,current_setting('test.a')::bigint,current_setting('test.epoch')::timestamptz), 'stale revision rejected');
select pg_temp.denied(format('select public.poll_answer(%s,repeat(''a'',72),array[-999]::bigint[],1,%L)',current_setting('test.multi')::bigint,current_setting('test.epoch')::timestamptz), 'foreign options rejected');
select pg_temp.assert((public.poll_answer(current_setting('test.multi')::bigint,repeat('a',72),array[current_setting('test.b')::bigint]::bigint[],1,current_setting('test.epoch')::timestamptz)->>'revision')::int = 2, 'answer changes replace previous selection');
select public.poll_answer(current_setting('test.multi')::bigint,repeat('b',72),array[current_setting('test.a')::bigint]::bigint[],0,current_setting('test.epoch')::timestamptz);
set local role authenticated;
select set_config('request.jwt.claims','{"email":"iamkcerb@gmail.com"}',true);
select pg_temp.assert((public.poll_library()->'results'->(current_setting('test.multi')::bigint)::text->>'respondents')::int = 2, 'totals count people once');
select pg_temp.assert((public.poll_library()->'results'->(current_setting('test.multi')::bigint)::text->'counts'->>(current_setting('test.a')::bigint)::text)::int = 1, 'replacing an answer removes its old option count');
select pg_temp.denied(format('select public.poll_save(%s,''Changed'','''',''multi'',array[''A'',''B''])',current_setting('test.multi')::bigint), 'answered question cannot be edited');
select public.poll_action(current_setting('test.multi')::bigint,'close');
set local role anon;
select pg_temp.denied(format('select public.poll_answer(%s,repeat(''a'',72),array[%s]::bigint[],2,%L)',current_setting('test.multi')::bigint,current_setting('test.a')::bigint,current_setting('test.epoch')::timestamptz), 'closed questions reject changes');
select pg_temp.assert(public.poll_current()->>'status' = 'closed', 'closed question remains visible');
set local role authenticated;
select set_config('request.jwt.claims','{"email":"iamkcerb@gmail.com"}',true);
select public.poll_action(current_setting('test.multi')::bigint,'open');
with fixture as (select public.poll_current()->>'opened_at' as new_epoch) select set_config('test.new_epoch', new_epoch::text, true) from fixture;
set local role anon;
select pg_temp.denied(format('select public.poll_answer(%s,repeat(''a'',72),array[%s]::bigint[],2,%L)',current_setting('test.multi')::bigint,current_setting('test.a')::bigint,current_setting('test.epoch')::timestamptz), 'queued changes from an earlier opening are rejected');
select pg_temp.assert(jsonb_array_length(public.poll_my_answer(current_setting('test.multi')::bigint,repeat('a',72))->'selection') = 1, 'reopening preserves responses');
select public.poll_answer(current_setting('test.multi')::bigint,repeat('a',72),'{}'::bigint[],2,current_setting('test.new_epoch')::timestamptz);
set local role authenticated;
select set_config('request.jwt.claims','{"email":"iamkcerb@gmail.com"}',true);
select pg_temp.assert((public.poll_library()->'results'->(current_setting('test.multi')::bigint)::text->>'respondents')::int = 1, 'clearing removes the browser from respondent totals');
select public.poll_action(current_setting('test.single')::bigint,'open');
with fixture as (select (public.poll_current()->'options'->0->>'id')::bigint as x, (public.poll_current()->'options'->1->>'id')::bigint as y, public.poll_current()->>'opened_at' as single_epoch) select set_config('test.x', x::text, true), set_config('test.y', y::text, true), set_config('test.single_epoch', single_epoch::text, true) from fixture;
select pg_temp.assert((select count(*) from jsonb_array_elements(public.poll_library()->'polls') p where p->>'status' = 'open') = 1, 'sending another question closes the previous one');
select pg_temp.assert((public.poll_library()->'results'->(current_setting('test.single')::bigint)::text->>'respondents')::int = 0, 'fresh questions have empty results');
set local role anon;
select pg_temp.denied(format('select public.poll_answer(%s,repeat(''a'',72),array[%s,%s]::bigint[],0,%L)',current_setting('test.single')::bigint,current_setting('test.x')::bigint,current_setting('test.y')::bigint,current_setting('test.single_epoch')::timestamptz), 'single-select rejects multiple choices');
select public.poll_answer(current_setting('test.single')::bigint,repeat('a',72),array[current_setting('test.x')::bigint]::bigint[],0,current_setting('test.single_epoch')::timestamptz);
select pg_temp.assert(public.poll_my_answer(current_setting('test.single')::bigint,repeat('a',72))->'selection' = to_jsonb(array[current_setting('test.x')::bigint]::bigint[]), 'single-select saves correctly');
select pg_temp.denied(format('select public.poll_answer(%s,''short'',array[%s]::bigint[],0,%L)',current_setting('test.single')::bigint,current_setting('test.x')::bigint,current_setting('test.single_epoch')::timestamptz), 'short ownership tokens rejected');
reset role;
select pg_temp.assert(not exists(select 1 from public.poll_answers where token_hash = repeat('a',72)), 'raw ownership secrets are never stored');
select 'All polling authorization assertions passed; test fixtures rolled back.' as result;
rollback;
