-- Transactional privacy and lifecycle checks; safe to rerun without leaving fixtures.
begin;
create function pg_temp.assert(ok boolean, description text) returns void language plpgsql as $$
begin if ok is distinct from true then raise exception 'FAIL: %', description; end if; raise notice 'PASS: %', description; end $$;
create function pg_temp.denied(query text, description text) returns void language plpgsql as $$
begin
  begin execute query; exception when others then raise notice 'PASS: % (%)', description, sqlerrm; return; end;
  raise exception 'FAIL: % was allowed', description;
end $$;
select pg_temp.assert(not has_table_privilege('anon','public.poll_write_ins','SELECT'), 'anonymous callers cannot read the write-in table');
select pg_temp.assert(not has_table_privilege('authenticated','public.poll_write_ins','SELECT'), 'signed-in callers cannot read the write-in table');
select set_config('test.first',gen_random_uuid()::text,true), set_config('test.second',gen_random_uuid()::text,true), set_config('test.third',gen_random_uuid()::text,true);
set local role authenticated;
select set_config('request.jwt.claims','{"email":"iamkcerb@gmail.com"}',true);
select set_config('test.poll',public.poll_save(null,'Write-in test','','single',array['A','B'])::text,true);
select public.poll_action(current_setting('test.poll')::bigint,'open');
select set_config('test.epoch',public.poll_current()->>'opened_at',true), set_config('test.option',public.poll_current()->'options'->0->>'id',true);
set local role anon;
select set_config('request.jwt.claims','{}',true);
select pg_temp.assert(public.poll_my_write_ins(current_setting('test.poll')::bigint,repeat('a',72)) = '[]'::jsonb, 'new browser starts with no suggestions');
select public.poll_write_in_save(current_setting('test.poll')::bigint,repeat('a',72),current_setting('test.first')::uuid,'First suggestion',0,current_setting('test.epoch')::timestamptz);
select public.poll_write_in_save(current_setting('test.poll')::bigint,repeat('a',72),current_setting('test.second')::uuid,'Second suggestion',0,current_setting('test.epoch')::timestamptz);
select pg_temp.assert(jsonb_array_length(public.poll_my_write_ins(current_setting('test.poll')::bigint,repeat('a',72))) = 2, 'multiple suggestions work even on single-select questions');
select pg_temp.assert(public.poll_my_write_ins(current_setting('test.poll')::bigint,repeat('b',72)) = '[]'::jsonb, 'another browser cannot see private suggestions');
select pg_temp.assert(not (public.poll_current() ? 'write_ins') and public.poll_current()::text not like '%First suggestion%', 'public current question never reveals suggestions');
select pg_temp.denied(format('select public.poll_write_in_save(%s,repeat(''b'',72),%L,''Hijacked'',1,%L)',current_setting('test.poll'),current_setting('test.first'),current_setting('test.epoch')), 'another browser cannot edit someone else’s suggestion');
select pg_temp.denied(format('select public.poll_write_in_save(%s,repeat(''b'',72),%L,null,1,%L)',current_setting('test.poll'),current_setting('test.first'),current_setting('test.epoch')), 'another browser cannot delete someone else’s suggestion');
select public.poll_write_in_save(current_setting('test.poll')::bigint,repeat('a',72),current_setting('test.first')::uuid,'First suggestion',0,current_setting('test.epoch')::timestamptz);
select pg_temp.assert(jsonb_array_length(public.poll_my_write_ins(current_setting('test.poll')::bigint,repeat('a',72))) = 2, 'retrying a saved suggestion does not duplicate it');
select public.poll_write_in_save(current_setting('test.poll')::bigint,repeat('a',72),current_setting('test.first')::uuid,'Revised suggestion',1,current_setting('test.epoch')::timestamptz);
select pg_temp.denied(format('select public.poll_write_in_save(%s,repeat(''a'',72),%L,''Stale edit'',1,%L)',current_setting('test.poll'),current_setting('test.first'),current_setting('test.epoch')), 'stale edits cannot overwrite new wording');
select pg_temp.assert(exists(select 1 from jsonb_array_elements(public.poll_my_write_ins(current_setting('test.poll')::bigint,repeat('a',72))) w where w->>'body' = 'Revised suggestion'), 'owner can restore edited text');
set local role authenticated;
select set_config('request.jwt.claims','{"email":"member@example.test"}',true);
select pg_temp.denied('select public.poll_library()', 'non-admin members cannot list class suggestions');
select set_config('request.jwt.claims','{"email":"iamkcerb@gmail.com"}',true);
select pg_temp.assert((public.poll_library()->'results'->current_setting('test.poll')->>'respondents')::int = 1, 'write-in-only participant counts once for multiple suggestions');
select pg_temp.assert(jsonb_array_length(public.poll_library()->'results'->current_setting('test.poll')->'write_ins') = 2, 'teacher sees all saved suggestions');
select pg_temp.assert((public.poll_library()->'results'->current_setting('test.poll')->'counts'->>current_setting('test.option'))::int = 0, 'write-ins do not add votes to prepared options');
select pg_temp.assert(not ((public.poll_library()->'results'->current_setting('test.poll')->'write_ins'->0) ? 'token_hash'), 'teacher results do not expose ownership tokens');
set local role anon;
select public.poll_answer(current_setting('test.poll')::bigint,repeat('a',72),array[current_setting('test.option')::bigint],0,current_setting('test.epoch')::timestamptz);
select public.poll_write_in_save(current_setting('test.poll')::bigint,repeat('b',72),current_setting('test.third')::uuid,'Another person',0,current_setting('test.epoch')::timestamptz);
set local role authenticated;
select set_config('request.jwt.claims','{"email":"iamkcerb@gmail.com"}',true);
select pg_temp.assert((public.poll_library()->'results'->current_setting('test.poll')->>'respondents')::int = 2, 'selecting and writing in still counts as one person');
select public.poll_action(current_setting('test.poll')::bigint,'close');
set local role anon;
select pg_temp.denied(format('select public.poll_write_in_save(%s,repeat(''a'',72),%L,''Closed edit'',2,%L)',current_setting('test.poll'),current_setting('test.first'),current_setting('test.epoch')), 'closed question prevents write-in changes');
set local role authenticated;
select set_config('request.jwt.claims','{"email":"iamkcerb@gmail.com"}',true);
select public.poll_action(current_setting('test.poll')::bigint,'open');
set local role anon;
select pg_temp.denied(format('select public.poll_write_in_save(%s,repeat(''a'',72),%L,''Old queued edit'',2,%L)',current_setting('test.poll'),current_setting('test.first'),current_setting('test.epoch')), 'old opening cannot accept queued suggestions');
select set_config('test.epoch',public.poll_current()->>'opened_at',true);
select pg_temp.assert(jsonb_array_length(public.poll_my_write_ins(current_setting('test.poll')::bigint,repeat('a',72))) = 2, 'reopening preserves suggestions');
select public.poll_write_in_save(current_setting('test.poll')::bigint,repeat('a',72),current_setting('test.first')::uuid,null,2,current_setting('test.epoch')::timestamptz);
select public.poll_write_in_save(current_setting('test.poll')::bigint,repeat('a',72),current_setting('test.first')::uuid,null,2,current_setting('test.epoch')::timestamptz);
select pg_temp.assert(jsonb_array_length(public.poll_my_write_ins(current_setting('test.poll')::bigint,repeat('a',72))) = 1, 'removal is retry-safe and hides the suggestion from its author');
select pg_temp.denied(format('select public.poll_write_in_save(%s,repeat(''a'',72),%L,''Resurrected'',3,%L)',current_setting('test.poll'),current_setting('test.first'),current_setting('test.epoch')), 'deleted suggestion cannot be accidentally resurrected');
select pg_temp.denied(format('select public.poll_write_in_save(%s,repeat(''a'',72),%L,''  '',0,%L)',current_setting('test.poll'),gen_random_uuid(),current_setting('test.epoch')), 'blank suggestions rejected');
select pg_temp.denied(format('select public.poll_write_in_save(%s,repeat(''a'',72),%L,repeat(''x'',2001),0,%L)',current_setting('test.poll'),gen_random_uuid(),current_setting('test.epoch')), 'oversized suggestions rejected');
set local role authenticated;
select set_config('request.jwt.claims','{"email":"iamkcerb@gmail.com"}',true);
select pg_temp.assert(jsonb_array_length(public.poll_library()->'results'->current_setting('test.poll')->'write_ins') = 2, 'teacher no longer sees the removed suggestion');
select public.poll_action(current_setting('test.poll')::bigint,'close');
select pg_temp.denied(format('select public.poll_save(%s,''Changed'','''',''single'',array[''A'',''B''])',current_setting('test.poll')), 'suggestions lock original question wording');
reset role;
select 'All private write-in assertions passed; fixtures rolled back.' as result;
rollback;
